language: csharp
solution: LAB09.sln

script:
  - xbuild /p:Configuration=Release LAB09.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit-console.exe ./LAB09/bin/Debug/nunit.framework.dll
